name: FarmGate Online
favicon: null
layout_spectrum: 0.9693648430984467
typography_spectrum: 0.6518722744658589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4958963147364557
  lightness: 0.17315406585112214
  saturation: 0.8773081908002496
  rhythmicContrast: 0.8401340101845562
purpose: []
